// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrxirwgropeyxulrksuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeGlyd2dyb3BleXh1bHJrc3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTE4MDMsImV4cCI6MjA2NzMyNzgwM30.G7-prYdf3OSPgFkAyBX8trGOvDJBVjYnRLyYR7IY7E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});